import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow-sm sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
            {/* Logo */}
            <div className="text-2xl font-bold text-blue-600">
              SIP<span className="text-gray-800">Planner</span>
            </div>

            {/* Main Navigation */}
            <nav className="hidden md:flex space-x-8 text-gray-700 font-medium">
              <Link href="/" className="hover:text-blue-600">
                Home
              </Link>
              <Link href="/sip" className="hover:text-blue-600">
                SIP Calculator
              </Link>
              <Link href="/mutualFunds" className="hover:text-blue-600">
                Mutual Funds
              </Link>
              <Link href="/articles" className="hover:text-blue-600">
                Articles
              </Link>
              <Link href="/contact" className="hover:text-blue-600">
                Contact
              </Link>
            </nav>

            {/* Auth Buttons */}
            <div className="flex space-x-4">
              <Link
                href="/login"
                className="px-4 py-2 border border-blue-600 text-blue-600 rounded-lg hover:bg-blue-50"
              >
                Login
              </Link>

              <Link
                href="/register"
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Register
              </Link>
            </div>
          </div>
        </header>

        {children}
        

        {/* ================= CTA + MINI FOOTER ================= */}
        <footer className="relative bg-white border-t border-gray-200">
          {/* CTA Section */}
          <div className="mx-auto max-w-6xl px-6 py-14 text-center">
            {/* Heading */}
            <h3 className="text-2xl md:text-3xl font-bold text-gray-900">
              Start Your Investment Journey
              <span className="block text-gray-600 font-semibold">
                With Confidence & Clarity
              </span>
            </h3>

            {/* Description */}
            <p className="mx-auto mt-4 max-w-2xl text-sm md:text-base text-gray-600">
              Plan SIPs, explore mutual funds, and make smarter long-term
              investment decisions with clarity.
            </p>

            {/* Action Buttons */}
            <div className="mt-8 flex flex-wrap justify-center gap-4">

              <Link
                href="/sip"
                className="rounded-xl bg-blue-100 border border-gray-300 px-7 py-3 text-sm
                   font-semibold text-gray-700 hover:bg-green-50 transition"
              >
                Calculate SIP
              </Link>

              <Link
                href="/mutualFunds"
                className="rounded-xl bg-blue-100 border border-gray-300 px-7 py-3 text-sm
                   font-semibold text-gray-700 hover:bg-green-50 transition"
              >
                Mutual Funds
              </Link>

              <Link
                href="/articles"
                className="rounded-xl bg-blue-100 border border-gray-300 px-7 py-3 text-sm
                   font-semibold text-gray-700 hover:bg-green-50 transition"
              >
                Articles
              </Link>

              <Link
                href="/contact"
                className="rounded-xl bg-blue-100 border border-gray-300 px-7 py-3 text-sm
                   font-semibold text-gray-700 hover:bg-green-50 transition"
              >
                Contact
              </Link>
            </div>

            {/* Trust Note */}
            <p className="mt-6 text-xs text-gray-500">
              No login required • Free to use • Market-linked estimates
            </p>

            {/* Left */}
            <p className="text-xs text-gray-500 pt-3">
              © {new Date().getFullYear()} SIP Planner. All rights reserved.
            </p>

            <div className="flex flex-col md:flex-row items-center justify-between gap-4">
              {/* Professional Links */}
              <div className="flex flex-wrap items-center gap-5 text-xs font-medium text-gray-600 pl-95 pt-3">
                <Link href="/about" className="hover:text-blue-600">
                  About
                </Link>

                <Link href="/privacy-policy" className="hover:text-blue-600">
                  Privacy Policy
                </Link>

                <Link href="/terms" className="hover:text-blue-600">
                  Terms & Conditions
                </Link>

                <Link href="/disclaimer" className="hover:text-blue-600">
                  Disclaimer
                </Link>
              </div>
            </div>
          </div>
        </footer>

      </body>
    </html>
  );
}
